---
title: "Home"
site: workflowr::wflow_site
author: "Wenjun Liu<br>Dame Roma Mitchell Cancer Research Laboratories<br>Adelaide Medical School<br>University of Adelaide"
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

Complete processing and analysis of single-nucleus RNA-Seq data from human mammary fibroblast cells.

* Mammary fibroblast cells were derived from pre-menopausal female donors with low MBD breasts. Cells were treated with DHT or with Empty Vehicle.
* Analyses completed include:
+ **Preprocess_fibro_from10x.Rmd**: 
1. Filtering, feature selection, normalization and scaling of all CellRanger outputs.
2. Dimension reduction and clsutering of cells. 
3. Selection of marker genes defining each cluster.

+ **Subtype_Prediction.Rmd**:
1. Unbiased cell type annotation using SingleR.

+ **Differential_Expression.Rmd**:
1. Global differential expression analysis. 
2. Differential expression analyses within each cluster. 
3. Cluster-specific pathway enrichment analysis using GOseq . 
4. Scoring individual cells against stem cell signatures using AUCell.

+ **RNA_Velocity.ipynb**: 
1. RNA velocity analysis using scVelo

